# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MonopolyGame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MonopolyGame
  pod 'FacebookLogin'
  pod 'Firebase'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestoreSwift'
  pod 'FirebaseStorageSwift'
  pod 'GoogleSignIn'
end
